name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ShellCheck
        run: shellcheck scripts/*.sh
      - name: yamllint
        run: |
          pip install yamllint
          yamllint -c .yamllint.yml argocd .github
